// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt1ppV3Tb-wakI_6t9Lb4pWUkZRrg-0n0',
    appId: '1:843729145245:android:d26e2c413378a336b13374',
    messagingSenderId: '843729145245',
    projectId: 'tecommerceapp-307c8',
    storageBucket: 'tecommerceapp-307c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALVMjwUeQ1dNCddl2-jnlVS_ahoqNlT04',
    appId: '1:843729145245:ios:2b768c71763bee8cb13374',
    messagingSenderId: '843729145245',
    projectId: 'tecommerceapp-307c8',
    storageBucket: 'tecommerceapp-307c8.appspot.com',
    androidClientId: '843729145245-hui5b5lbfqdr66na2kj68um6orobgv33.apps.googleusercontent.com',
    iosClientId: '843729145245-5qnetuft28sf9giiufobtb9nvr2jktq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tEcommerceProject',
  );

}